services:
  app:
    build:
      context: .
    restart: unless-stopped
    container_name: app
    networks:
      - app
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx-conf.d:/etc/nginx/conf.d
      - etc-letsencrypt:/etc/letsencrypt
    depends_on:
      - app
    networks:
      - app
  certbot:
    image: certbot/certbot
    depends_on:
      - nginx
    container_name: certbot
    profiles:
      - ssl
    volumes:
      - etc-letsencrypt:/etc/letsencrypt
    command:
      - certonly --email nikitatsarenko7@gmail.com --agree-tos --no-eff-email -d ${DOMAIN_NAME}

volumes:
  etc-letsencrypt:
networks:
  app: