services:
  app:
    build:
      context: .
    networks:
      - dev
  ngnix:
    image: nginx:stable-alpine
    ports:
      - 80:80
      - 443:80
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - app
    networks:
      - dev

networks:
  dev: